// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEMS5_YgeyMeUBGjDubL1bNQYFnxC7TtY',
    appId: '1:282451240892:web:04a420eb0541fc17546db9',
    messagingSenderId: '282451240892',
    projectId: 'notes-e-f34e2',
    authDomain: 'notes-e-f34e2.firebaseapp.com',
    storageBucket: 'notes-e-f34e2.firebasestorage.app',
    measurementId: 'G-YGG8XS7GXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvYb_YxXTucjgNJRioTWsLpE8u2yJP5SQ',
    appId: '1:282451240892:android:8e607ca2536bc142546db9',
    messagingSenderId: '282451240892',
    projectId: 'notes-e-f34e2',
    storageBucket: 'notes-e-f34e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Hm78i60SfY66q1Ievl4T92L6azic6Io',
    appId: '1:282451240892:ios:f7cd898b8318739d546db9',
    messagingSenderId: '282451240892',
    projectId: 'notes-e-f34e2',
    storageBucket: 'notes-e-f34e2.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Hm78i60SfY66q1Ievl4T92L6azic6Io',
    appId: '1:282451240892:ios:f7cd898b8318739d546db9',
    messagingSenderId: '282451240892',
    projectId: 'notes-e-f34e2',
    storageBucket: 'notes-e-f34e2.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEMS5_YgeyMeUBGjDubL1bNQYFnxC7TtY',
    appId: '1:282451240892:web:8b1de9d280662db8546db9',
    messagingSenderId: '282451240892',
    projectId: 'notes-e-f34e2',
    authDomain: 'notes-e-f34e2.firebaseapp.com',
    storageBucket: 'notes-e-f34e2.firebasestorage.app',
    measurementId: 'G-E2LDE7KBW5',
  );

}